AWSTemplateFormatVersion: '2010-09-09'

Description: Example stack that deploys AWS, Azure and Google Cloud resources.

Transform:
- MultiCloud

Resources:

    myGoogleCloudInstance:
        Type: GoogleCloud::Compute::Instance
        Properties:
            Name: my-gce-instance
            Project: cfnmulticlouddemo
            Zone: us-west2-a
            MachineType: f1-micro
