AWSTemplateFormatVersion: '2010-09-09'

Description: Example stack that deploys AWS, Azure and Google Cloud resources.

Transform:
- MultiCloud

Resources:

    myAzureResourceGroup:
        Type: Azure::Resource::ResourceGroup
        Properties:
            Name: myAzureResGroup
            Location: westus

    myAzureVirtualNetwork:
        Type: Azure::Network::VirtualNetwork
        Properties:
            Name: myAzureVNet
            ResourceGroupName: !GetAtt myAzureResourceGroup.Name
            Location: !GetAtt myAzureResourceGroup.Location
            AddressSpace:
                AddressPrefixes:
                    - '10.0.0.0/16'
    
    myAzureSubnet:
        Type: Azure::Network::Subnet
        Properties:
            Name: myAzureSubnet
            ResourceGroupName: !GetAtt myAzureResourceGroup.Name
            VirtualNetworkName: !GetAtt myAzureVirtualNetwork.Name
            AddressPrefix: '10.0.0.0/24'
    
    myAzureNetworkInterface:
        Type: Azure::Network::NetworkInterface
        Properties:
            Name: myAzureNIC
            ResourceGroupName: !GetAtt myAzureResourceGroup.Name
            Location: !GetAtt myAzureResourceGroup.Location
            IpConfigurations:
                - Name: myIpConfig
                  Subnet:
                    Id: !GetAtt myAzureSubnet.Id

    myAzureVirtualMachine:
        Type: Azure::Compute::VirtualMachine
        Properties:
            Name: myAzureVm
            ResourceGroupName: !GetAtt myAzureResourceGroup.Name
            Location: !GetAtt myAzureResourceGroup.Location
            OsProfile:
                ComputerName: my-box
                AdminUsername: myadminusername
                AdminPassword: Super$ecret!!
            HardwareProfile:
                VmSize: Standard_DS1_v2
            StorageProfile:
                ImageReference:
                    Publisher: Canonical
                    Offer: UbuntuServer
                    Sku: 16.04.0-LTS
                    Version: latest
            NetworkProfile:
                NetworkInterfaces:
                    - Id: !GetAtt myAzureNetworkInterface.Id
