AWSTemplateFormatVersion: '2010-09-09'

Description: Example stack that deploys AWS, Azure and Google Cloud resources.

Transform:
- MultiCloud

Resources:

    myAzureResourceGroup:
        Type: Azure::Resource::ResourceGroup
        Properties:
            Name: myAzureResGroupForQueue
            Location: westus

    myAzureStorageAccount:
        Type: Azure::Storage::StorageAccount
        Properties:
            Name: cfnmulticloudqueuedemo
            ResourceGroupName: !GetAtt myAzureResourceGroup.Name
            Location: !GetAtt myAzureResourceGroup.Location
            Kind: StorageV2
            Sku:
                Name: Standard_LRS

    myAzureQueue:
        Type: Azure::Storage::Queue
        Properties:
            Name: myqueue
            ResourceGroupName: !GetAtt myAzureResourceGroup.Name
            AccountName: !GetAtt myAzureStorageAccount.Name
