AWSTemplateFormatVersion: '2010-09-09'

Description: Example stack that deploys AWS, Azure and Google Cloud resources.

Transform:
- MultiCloud

Resources:

    myGoogleCloudNetwork:
        Type: GoogleCloud::Compute::Network
        Properties:
            Name: mynetwork
            Project: cfnmulticlouddemo
            Region: us-west2
            Description: Sample Network
            RoutingConfig:
                RoutingMode: REGIONAL
            AutoCreateSubnetworks: false

    myGoogleCloudSubnetwork:
        Type: GoogleCloud::Compute::Subnetwork
        Properties:
            Name: mysubnetwork
            Project: cfnmulticlouddemo
            Region: us-west2
            Network: !GetAtt myGoogleCloudNetwork.Name
            Description: Sample Subnetwork
            PrivateIpGoogleAccess: false
            EnableFlowLogs: false
            IpCidrRange: "10.0.0.0/24"

    myGoogleCloudInstance:
        Type: GoogleCloud::Compute::Instance
        Properties:
            Name: my-gce-instance
            Project: cfnmulticlouddemo
            Zone: us-west2-a
            MachineType: f1-micro
            Disks:
              - Boot: true
                AutoDelete: true
                InitializeParams:
                    SourceImage:
                        Project: debian-cloud
                        Family: debian-9
            NetworkInterfaces:
              - Subnetwork:
                    Project: cfnmulticlouddemo
                    Region: us-west2
                    Name: !GetAtt myGoogleCloudSubnetwork.Name
                AccessConfigs:
                  - Type: ONE_TO_ONE_NAT
                    Name: External NAT
            ServiceAccounts:
              - Email: default
                Scopes:
                  - devstorage.read_write
                  - logging.write